version: '3.7'

services:
  server:
    build:
      context: .
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: exo-planets-api 
    restart: 'unless-stopped'
    ports:
      - '3336:3336'
    volumes:
      - ./:/app
      - /app/node_modules

# For mac users        
# volumes:
  #nfsmount:
    #driver: local
    #driver_opts:
      #type: nfs
      #o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      #device: ":/System/Volumes/Data/${PWD}"

